config/routes.rb
Whitewalls::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root 'home#index'

  resources :artists, only: :show
  resources :artworks, only: [:index, :show]
  resources :collections, only: :show
  resources :orders, only: :create

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :artworks

	validates_presence_of :name
end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
	belongs_to :artist

	mount_uploader :image, ImageUploader

	paginates_per 14

	validates_presence_of :title, :year, :price, :artist, :image

	scope :newest, order: 'created_at DESC'

	belongs_to :collection
end

app/models/collection.rb
class Collection < ActiveRecord::Base
	mount_uploader :image, ImageUploader
  mount_uploader :preview_image, ImageUploader

	validates_presence_of :title, :description

	has_many :artworks
end

app/models/order.rb
class Order
  include ActiveModel::Model
  extend ActiveModel::Naming

  attr_accessor :artwork, :email, :name, :address, :comment, :phone, :ip, :created_at
  validates_presence_of :artwork, :email

  def notify_admin
    OrderMailer.new_order(self).deliver
  end

  def artwork_id=(id)
    @artwork = Artwork.find id
  end

  def persisted?
    false
  end
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	def show
		@artist = Artist.find params[:id]
	end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  def index
  	@artworks = Artwork.newest.page params[:page]
  end

  def show
  	# TODO: refactor this with scopes or any
  	@artwork      = Artwork.find params[:id]
  	@artist_works = @artwork.artist.artworks.where('id != ?', @artwork.id).limit(6)
  	@other_works  = Artwork.where('id NOT IN (?)', @artist_works.ids << @artwork.id).limit(9)
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def show
  	@collection = Collection.find params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@collections = Collection.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    order = Order.new params[:order].merge({ ip: request.remote_ip, created_at: Time.now })
    order.notify_admin
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js   { }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def in_rubbles(price)
		number_to_currency(price, unit: "руб.", format: "%n %u", precision: 0, delimiter: ' ')
	end

	def current_page
		params[:page] || 1
	end

	def title
		content_for?(:title) ? content_for(:title) : 'Проблемы белых стен - Искусство рядом. Тиражная графика современных художников'
	end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/artists/show.html.slim
- content_for :title
  = "#{@artist.name} - Проблемы белых стен"
- content_for :description
  = "#{@artist.name} - #{@artist.bio}".truncate(200)
.artist-name
	= @artist.name.html_safe
.artist-bio
	= @artist.bio.html_safe
.artworks
	h2 Все принты этого автора
	= render @artist.artworks

app/views/artworks/_artwork.html.slim
.artwork
  .image= link_to image_tag(artwork.image.preview.url), artwork
  = link_to artwork.artist.name, artwork, class: "artist"
  = link_to artwork.title, artwork, class: "title"
  = link_to in_rubbles(artwork.price), artwork, class: "price"

app/views/artworks/_group.html.slim
.group class="page-#{current_page}"
	.big
		- if large = group.shift
			= render 'artworks/large', artwork: large
	.other
		= render group

app/views/artworks/_large.html.slim
= render 'layouts/buy_popup', artwork: artwork
.big
  .large
    .wrapper
      = link_to image_tag(artwork.image.medium.url), artwork.image.url, class: [ "link", "image-link" ]
      .content
        = link_to artwork.artist.name, artwork.artist, class: "author"
        = link_to artwork.title, artwork, class: "title"
        .description= artwork.description.html_safe
        .price= in_rubbles(artwork.price)
        #buy-print.buy data-popup-id='buy-popup-#{ artwork.id }' = "Купить принт"
      .share
        .share-message Поделиться с друзьями:
        ul
          li.icon
            / TODO: move it to helper
          	a.fb target="_blank" rel="nofollow" href="http://www.facebook.com/sharer/sharer.php?u=#{ artwork_path artwork, only_path: false }" f 
          li.icon
            a.vk target="_blank" href="http://www.vk.com/share.php?url=#{ artwork_path artwork, only_path: false }" v

app/views/artworks/index.html.slim
- content_for :title
  | Все принты - Галерея принтов современных художников
- names = @artworks.map(&:artist).map(&:name).uniq
- content_for :description
  = "Купить работы - #{names.join(', ')}"
- @artworks.in_groups_of(7, false) do |group|
	= render 'artworks/group', group: group
.pagination-wrapper
  = paginate @artworks

app/views/artworks/show.html.slim
- content_for	:facebook_image
	= @artwork.image.medium.url
- if @artwork.description
	- content_for :facebook_description
		= strip_tags @artwork.description
- content_for :title
	= "#{@artwork.artist.name} - #{@artwork.title} - Проблемы белых стен"
- content_for :description
  = "#{@artwork.artist.name} - #{@artwork.title} - #{@artwork.description}".truncate(200)
.artwork
	- if @artwork.collection
		h1.collection-name-top
			= @artwork.collection.title
	= render partial: 'artworks/large', locals: { artwork: @artwork }
	.artist-works
		h2 Другие принты этого художника
		= render @artist_works
	.other-works
		h2 Принты других художников
		= render @other_works

app/views/collections/show.html.slim
- content_for :title
	= "#{@collection.title} - Проблемы белых стен"
- content_for :description
  = "#{@collection.title}. #{@collection.description}".truncate(200)
.collection-show
  .bg-collection-overlay
  .bg-collection-show style="background: url('#{@collection.image.url}'); background-size: cover;"
    .collection-info
      .title= @collection.title.html_safe
      .description= @collection.description.html_safe
.artworks-collections
  - @collection.artworks.each do |artwork|
    = render artwork

app/views/home/index.html.slim
- content_for :facebook_image
  = image_url 'for-facebook.jpg'
- content_for :facebook_description
  | Искусство рядом. Тиражная графика современных художников.
- content_for :description
  | Проблемы белых стен - купить фотографии, тиражную графику, принты известных современных художников. Онлайн-галерея для существующих и начинающих коллекционеров современного искусства. Оригинальное искусство для вашего дома и интерьера.
#image-wrapper
.headline
  h1.main-headline Искусство рядом. Тиражная графика современных художников
#collections-mainpage
  .top-collections
    - banner_collections = @collections.shift(3)
    .banner
      .jcarousel-wrapper
        .jcarousel-control-prev = image_tag("arrow_left.svg")
        .jcarousel-control-next = image_tag("arrow_right.svg")
        .jcarousel
          ul
            - banner_collections.each do |collection|
              li
                .collection
                  .bg-collection
                  .image style="background: url('#{collection.image.url}'); background-size: cover;" = link_to " ", collection_path(collection)
                  .title= link_to collection.title, collection_path(collection)
                  .button= link_to 'Посмотреть коллекцию', collection_path(collection)
        p.jcarousel-pagination
  h2.colletions-title Другие коллекции
  .collections-wrapper
    - @collections.each do |collection|
      .collection
        .image= link_to image_tag(collection.preview_image.url || collection.image.url), collection_path(collection)
        .title= link_to collection.title, collection_path(collection)
  .centered-link-wrapper
    =link_to 'Все принты', artworks_path

app/views/layouts/_about_popup.slim
.popup-wrapper
  .transparent
  .popup-close = image_tag("close.svg")
  .about-popup
    .about-text &laquo;Проблемы белых стен&raquo; занимается выпуском эксклюзивных коллекций тиражной графики современных художников, продажей авторских принтов музейного качества со&nbsp;всего мира и&nbsp;формированием частных и&nbsp;корпоративных собраний.
    p В&nbsp;основе проекта&nbsp;&mdash; идея о&nbsp;том, что жить с&nbsp;искусством может позволить себе каждыи&#774;. Мы&nbsp;делаем искусство более доступным и&nbsp;занимаемся популяризациеи&#774; демократичного коллекционирования.
    p Искусство в&nbsp;личном пространстве&nbsp;&mdash; глобальный тренд, который приходит в&nbsp;Россию. Выстраивать мир, в&nbsp;котором живешь с&nbsp;помощью предметов искусства это не&nbsp;только желание быть частью модного феномена и&nbsp;культурной игры, но&nbsp;и&nbsp;самоидентефикация, зеркало представлений владельца о&nbsp;самом себе.
    p Тиражный авторский принт, работа на&nbsp;бумаге&nbsp;&mdash; отличный &laquo;строительный материал&raquo; для фундамента частной коллекции. Это находка для тех, кто только начинает задумываться о&nbsp;том, чем занять вакантное место на&nbsp;стене.
    .facebook = link_to "Мы в Facebook", "https://www.facebook.com/whitewallsproblems", target: "blank", class: 'button-popup'

app/views/layouts/_buy_popup.slim
.popup-wrapper-buy id='buy-popup-#{ artwork.id }'
  .transparent
  .popup-close = image_tag("close.svg")
  .buy-form
    h2 Купить принт
    .form
      = simple_form_for Order.new, remote: true do |f|
        = f.input :name
        = f.input :email
        = f.input :address
        = f.input :phone
        = f.input :comment, as: :text
        = f.hidden_field :artwork_id, value: artwork ? artwork.id : @artwork.id
        .buy-popup = f.submit

app/views/layouts/_contacts_popup.slim
.popup-wrapper-contacts
  .transparent
  .popup-close = image_tag("close.svg")
  .about-popup.contacts-popup
    .phone +7 916 706 40 36
    .email = mail_to 'hello@whitewallsproblems.com'
    .facebook = link_to "Мы в Facebook", "https://www.facebook.com/whitewallsproblems", target: "blank", class: 'button-popup'

app/views/layouts/_facebook_og_tags.html.slim
- if content_for?(:facebook_title)
	meta property="og:title" content="#{ yield :facebook_title }"
- if content_for?(:facebook_description)
	meta property="og:description" content="#{ yield :facebook_description }"
- if content_for?(:facebook_image)
	meta property="og:image" content="#{ yield :facebook_image }"

app/views/layouts/_footer.html.slim
.footer
  .footer-wrapper
    .partners
      p Пресса о нас:
      a href="http://www.elle.ru/elledecoration/names/iskusstvo-v-interere-avtorskie-kollektsii/4/" target="_blank"
        = image_tag("elle.jpg")
      a.buro href="http://www.buro247.ru/culture/news/onlayn-platformy-dlya-pokupki-iskusstva.html" target="_blank"
        = image_tag("buro.jpg")
      a.blou href="http://blogs.artinfo.com/russianews/2013/12/13/%D0%B8%D1%81%D0%BA%D1%83%D1%81%D1%81%D1%82%D0%B2%D0%BE-%D0%BD%D0%B5-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D0%BE-%D1%81%D1%82%D0%BE%D0%B8%D1%82%D1%8C-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D1%8B-%D0%BF/" target="_blank"
        = image_tag("blou.jpg")
      a.pop href="http://www.peopleofprint.com/pop/support-our-kickstarter-campaign-print-isnt-dead/" target="_blank"
        = image_tag("pop.jpeg")
      a href="http://oilyoil.com/ru/blog/masha-kovalevskaya-about-how-to-buy-your-first-art-work-and-start-live-with-art" target="_blank"
        = image_tag("oil.jpg")
      a.tnp href="http://theoryandpractice.ru/posts/9208-i-love-prints" target="_blank"
        = image_tag("tnp.png")
  .other-content
    .copywrite © 2014 Проблемы белых стен
  	= render 'layouts/menu_footer'
    = render 'layouts/social'

  img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=260044464193203&amp;ev=NoScript"

app/views/layouts/_google_analytics.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52210511-1', 'auto');
  ga('send', 'pageview');

app/views/layouts/_header.html.slim
.header class="#{params[:controller]}"
  = render 'layouts/menu'

app/views/layouts/_menu.html.slim
ul.menu-right
  li#about-popup.transparent-menu
    = "О нас"
  li#about-popup-contacts.transparent-menu 
    = "Контакты"
.logo class="page-#{current_page}"
  = link_to image_tag("logo.svg"), root_path
ul.menu-left
  li.transparent-menu = link_to 'Все принты', artworks_path, class: ('active' if current_page?(artworks_path))
  li.transparent-menu 
    a href="http://blog.whitewalls.gallery/" target="blank" Блог

app/views/layouts/_menu_footer.slim
ul.menu
  li= link_to 'Все принты', artworks_path
  li 
    a href="http://blog.whitewalls.gallery/" target="blank" Блог

app/views/layouts/_metatags.slim
- if content_for?(:description)
  meta name="description" content="#{ yield :description }"

app/views/layouts/_social.html.slim
ul.social
  li.icon = link_to "f", "https://www.facebook.com/whitewallsproblems", target: "_blank", class: "fb"

app/views/layouts/application.html.slim
doctype html
html
  head
    title= title
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
    = render 'layouts/metatags'
    = render 'layouts/facebook_og_tags'
  body
  	= render 'layouts/header'
    .content = yield
    = render 'layouts/footer'
    = render 'layouts/about_popup'
    = render 'layouts/contacts_popup'

app/views/layouts/mail.html.slim
doctype html
html
  head
    meta content='text/html; charset=UTF-8' http-equiv='Content-Type'
  body
    = yield